### ISSUE TITLE
urllib quote_plus

### ISSUE THREAD

**Issue by lukasszz** [tghw/trello-py#4]
From Python 3.4 quote_plus is moved to urlib.parse, for that version you have to change the import in trello.**init**.py:

from urllib.parse import quote_plus

**Comment by roman-ku** [comment]
So 2 years later, this issue is still not solved meaning this library can't be used with Python3.

**Comment by machinekoder** [comment]
Wow, that's terrible.

**Comment by tghw** [comment]
Feel free to submit a pull request.

**Comment by drop-db** [comment]
Is there a fix?

**Comment by therealrobster** [comment]
Is there no support for python3?

**Comment by kulikjak** [comment]
What exactly is a problem? I fixed some issues in this library more than two years ago and am using it happily ever since (with Python 3.6 I believe). Can you be more specific if you are still encountering problems?

**Comment by therealrobster** [comment]
I am sorry, I should have said.  I was getting the error RE urllib.parse and quote_plus.  I'll dig in with some variations on python3 and see what I can find.

**Comment by kulikjak** [comment]
The current source code here does not contain quote_plus. I believe that your problem might be caused by the fact that you are using the latest version from Pypi and not from here. Sadly, trello-py with changes fixing python 3 compatibility was never released :(.

There is another issue asking for the pypi release, but sadly the original author was quiet for some time now...
